name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Build Docker Image
        run: docker build --platform linux/amd64 -t anasnevrekar/real-time-messaging-platform:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: docker push anasnevrekar/real-time-messaging-platform:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY_B64 }}" | base64 --decode > /tmp/ec2-key.pem
          chmod 600 /tmp/ec2-key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i /tmp/ec2-key.pem \
            ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'

          docker pull anasnevrekar/real-time-messaging-platform:latest

          docker stop real-time-messaging-platform || true
          docker rm real-time-messaging-platform || true

          docker run -d \
            --name real-time-messaging-platform \
            --env-file /home/ec2-user/.env \
            -p 3000:3000 \
            anasnevrekar/real-time-messaging-platform:latest

          EOF